[build]
  command = "npm run build"  # Or "vite build" - matches your package.json script
  publish = "dist"           # Vite's default output directory
  functions = "netlify/functions" # Tells Netlify where the functions are

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 # Use 200 for function calls (like a rewrite)